# Generated by Django 3.1.7 on 2021-07-03 20:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('emoji', models.CharField(blank=True, max_length=2)),
                ('slug', models.SlugField(blank=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('publisher', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=400)),
                ('summary', models.CharField(blank=True, max_length=50000)),
                ('reduced_by', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('error', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=400)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('thumbnail', models.URLField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=140)),
                ('domain', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('preview', models.BooleanField(default=False)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='url_checker.archive')),
            ],
            options={
                'unique_together': {('archive', 'url')},
            },
        ),
    ]
